"""Add employment column to User table

Revision ID: 398382076fab
Revises: 
Create Date: 2023-05-29 13:49:08.105414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '398382076fab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_employment'), ['employment'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_employment'))
        batch_op.drop_column('employment')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index('ix_company_company_name', ['company_name'], unique=False)
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
