"""Add start_time2 column to opening_hours table

Revision ID: 59c58c09e1ac
Revises: a5852a4b2339
Create Date: 2023-08-23 21:23:16.146747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c58c09e1ac'
down_revision = 'a5852a4b2339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opening_hours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time2', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time2', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opening_hours', schema=None) as batch_op:
        batch_op.drop_column('end_time2')
        batch_op.drop_column('start_time2')

    # ### end Alembic commands ###
